### PR TITLE
Added ReferenceCardinality to provider ApplicationHandler. Added addr…

### PR DESCRIPTION
**Pull request by ghost**
…essbook application but fails to resolve

### CODE REVIEW

**Comment by ghost** [comment]
This is my first PR, treat me gently. Not sure if it is correct.

**Comment by pkriens** [comment]
Very nice! This is a much better looking website than the button. 

However, a number of issues that need to be fixed:
- IPR – First you need to sign off the commits so it is clear you own this intellectual property and contribute it under an Apache 2 license.I think you based this on the Vaadin license which is Apache 2.0 so that should be ok. It is my fault that I forgot to add the Contribution file. See https://github.com/osgi/osgi.enroute.examples/blob/master/CONTRIBUTING.md
- One of the first rules in OSGi, and that means triple that rule in enRoute, is to NOT have static links. Statics and class name based loading is evil :-) Your Contact service should be, eh, a service. It currently has the root of all evil: a static factory method! :-) The hardest part of the silly example I prepared was to make it properly service based. So now your AddressbookApplication can use a Reference to a ContactService and the ContactService can be a real OSGi service.
- In OSGi enRoute we're quite crazy about DTOs instead of beans. In the example you drag in a few dependencies that should not be necessary. I've taken your code and modified to use the DTOs service in OSGi enRoute. I actually created a DTOItem<T> and a DTOContainer<T> that are a simplistic variant of the Bean\* counterparts.

I suggest you update the PR to contain your Sign-offs. I will then merge this is a separate branch and provide my proposed changes. We can then discuss if you want to go along with it. Ok?

**Comment by ghost** [comment]
On 7/06/2016 8:43 PM, Peter Kriens wrote:

> Very nice! This is a much better looking website than the button.
> 
> However, a number of issues that need to be fixed:
> - IPR – First you need to sign off the commits so it is clear you own this intellectual property
>   and contribute it under an Apache 2 license.I think you based this on the Vaadin license which
>   is Apache 2.0 so that should be ok. It is my fault that I forgot to add the Contribution file.
>   See https://github.com/osgi/osgi.enroute.examples/blob/master/CONTRIBUTING.md
> 
> Shall do.
> 
>  *
> - One of the first rules in OSGi, and that means triple that rule in enRoute, is to NOT have
>   static links. Statics and class name based loading is evil :-) Your Contact service should be,
>   eh, a service. It currently has the root of all evil: a static factory method! :-) The hardest
>   part of the silly example I prepared was to make it properly service based. So now your
>   AddressbookApplication can use a Reference to a ContactService and the ContactService can be a
>   real OSGi service.
> 
> I only took the Vaadin example as was as a first attempt to get involved in the PR process etc..
> - In OSGi enRoute we're quite crazy about DTOs instead of beans. In the example you drag in a
>   few dependencies that should not be necessary. I've taken your code and modified to use the
>   DTOs service in OSGi enRoute. I actually created a DTOItem and a DTOContainer that are a
>   simplistic variant of the Bean\* counterparts.

I look forward to how you handle DTOs, up til now I have been using the Kryo serialization code and 
they use very simple classes as well.

> I suggest you update the PR to contain your Sign-offs. I will then merge this is a separate branch 
> and provide my proposed changes. We can then discuss if you want to go along with it. Ok?
> 
> Paul

**Comment by pkriens** [comment]
The DTOs in OSGi enRoute extend the OSGi DTO class. Currently they are serialized to JSON with the DTOs service but it should work with Jackson, etc. since only public fields are used.

In OSGi enRoute example I'd like to stick to one standard though there are many reasons in practice to choose other ways of working. However, from a single uniform way it is easier for people to pickup the core parts of examples; in this case Vaadin.

**Comment by ghost** [comment]
Not sure if the sign off is OK but here goes..

**Comment by bjhargrave** [comment]
> Not sure if the sign off is OK but here goes..

You need to amend your commits so that each commit message includes a `Signed-off-by` as required by CONTRIBUTING. Then push force your updated commits. Thanks.

**Comment by pkriens** [comment]
Why did you close it? I really liked the contribution.

I know the rules are a pita but we need to follow them because we have some really big companies in the OSGi Alliance that can't run the risk of being involved with anything but pristine pedigree.

**Comment by ghost** [comment]
Hi Peter,

I closed it because I would like to have a clean presentation for the PR.

Today I have been trying to work out how to change the commit message on the one commit in question 
and it seems I would have to rebase interactive which I have not been able to achieve.

I am redoing the code and will present a clean PR to the rules "real soon now" :-)

Being determined to have EnRoute with Vaadin central to my project, I have to persevere so, stand by.

Paul

**Comment by pkriens** [comment]
I've created a branch with the changes I made to your code to make it more OSGi

https://github.com/osgi/osgi.enroute.examples.vaadin/tree/diderotnet-master/osgi.enroute.examples.vaadin.addressbook.application

**Comment by pkriens** [comment]
We might move the DTOContainer and DTOItem to a util in enroute.bundles if this is an interesting approach

**Comment by ghost** [comment]
Peter,

Not sure if I am making claim to your changes, but I think the PR should be OK, fingers crossed.

I have not looked in detail at the DTO code yet, but I think you are referring to the Vaadin 
approach to data items and containers.

If so, an EnRoute util sounds fine to me.

Paul

**Comment by pkriens** [comment]
I’ve made a branch with some changes. I removed some remains and updated the readme file. Also updated the bndrun file to work out of the box, it did not require the theme and pre-compiled widget bundles.

If you can take a look and say it is ok then I merge it with the main branch.

https://github.com/osgi/osgi.enroute.examples.vaadin/tree/update https://github.com/osgi/osgi.enroute.examples.vaadin/tree/update

Nice work, thanks! Kind regards,

```
Peter Kriens
```

**Comment by ghost** [comment]
Peter,

It will be a very impressive example.

Thanks for undertaking the Vaadin exploration. I think the example gives a good coverage of EnRoute 
abilities and potential.

Bedtime here now, get to it early tomorrow.

Paul

**Pull request closed without merging**
